### ISSUE TITLE
Typo in README.md

### ISSUE THREAD

**Issue by uid66** [jjatria/perl-opentelemetry-sdk#14]
Odd name/value argument for subroutine 'OpenTelemetry::SDK::Trace::Span::add_event'

https://github.com/jjatria/perl-opentelemetry-sdk/blob/20bc2e0c66bd8de06a1088450789d2e7a96fd119/README.md?plain=1#L99

**Comment by jjatria** [comment]
Well spotted! Yeah, that should be an event in `foo`, since the `bar` span hasn't been created at that point.
