### ISSUE TITLE
`bignum` causes issues with `CLDR::Number` and possibly others

### ISSUE THREAD

**Issue by hangy** [jjatria/perl-opentelemetry-sdk#16]
I recently tried adding `OpenTelemetry::SDK v0.22` to a project that also uses `CLDR::Number v0.19`. As soon as `use OpenTelemetry::SDK` is added, the following error causes a compilation error.

> Can't locate object method "ffround" via package "Math::BigInt" at <path_to>/perllib/CLDR/Number/Role/Format.pm line 26

This seems to be related to `bignum` changes in Perl 5.36 and higher. [`Locale::CLDR` had the same issue](https://github.com/ThePilgrim/perlcldr/issues/39) and fixed it in v0.34.2 by using `bigfloat` instead of `bignum`.

Would a similar fix be feasible for `OpenTelemetry::SDK`? 

## Related links

- ThePilgrim/perlcldr#36
- ThePilgrim/perlcldr#39
- patch/cldr-number-pm5#52

**Comment by jjatria** [comment]
Thanks for the report! This is not the first issue we've had with bignum (see #3). I'll look into this as soon as possible. If other projects have also encountered a similar issue and found solutions, I would imagine we could definitely do something like that here.

**Comment by jjatria** [comment]
What a weird bug this was...

I've just pushed 487f204 to fix this, but I'll keep this issue open until I get a release out to CPAN. The only reason why I haven't released this already is because I'm testing a trial release for log support. I'll try to get this out as soon as possible.

Thanks again for the report!

**Comment by hangy** [comment]
Thanks a lot for the super quick fix! I can confirm that the error no longer occurs after I installed `OpenTelemetry::SDK` from Git.

I'm looking forward to experimenting with this OTel SDK. Great job, BTW! 👍

**Comment by jjatria** [comment]
I've just released 0.024 to CPAN which should include this change. It should be indexed by PAUSE shortly.
